name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # Otherwise egl initialisation fails
  # In CI we don't have a display-surface to render to
  EGL_PLATFORM: surfaceless
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: echo "MLN_PRECOMPILE=0" >> $GITHUB_ENV
      - run: echo "MLN_CORE_LIBRARY_USE_AMALGAM=0" >> $GITHUB_ENV
      - run: rustup update stable && rustup default stable && rustup component add rustfmt && rustup component add clippy
      - uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
        with: { tool: 'just' }
      - run: just env-info install-dependencies 'vulkan'
      - run: just ci-lint
  test:
    name: Test ${{ matrix.runs-on }} - ${{ matrix.backend }} - Precompiled ${{ matrix.precompiled }}
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86
          - runs-on: ubuntu-latest
            backend: vulkan
            precompiled: 0
            amalgam: 0
          # - runs-on: ubuntu-latest
          #   backend: vulkan
          #   precompiled: 1
          #   amalgam: 1
          - runs-on: ubuntu-latest
            backend: opengl
            precompiled: 0
            amalgam: 0
          # Linux ARM
          - runs-on: ubuntu-24.04-arm
            backend: vulkan
            precompiled: 0
            amalgam: 0
          # macOS ARM
          - runs-on: macos-latest
            backend: metal
            precompiled: 0
            amalgam: 0
          - runs-on: macos-latest
            backend: vulkan
            precompiled: 0
            amalgam: 0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
        with: { tool: 'just' }
      - run: echo "MLN_PRECOMPILE=${{ matrix.precompiled }}" >> $GITHUB_ENV
      - run: echo "MLN_CORE_LIBRARY_USE_AMALGAM=${{ matrix.amalgam }}" >> $GITHUB_ENV
      - run: just env-info install-dependencies '${{ matrix.backend }}'
      - if: startsWith(matrix.runs-on, 'macos') && matrix.backend == 'vulkan'
        run: |
          echo "VK_ICD_FILENAMES=$(brew --prefix molten-vk)/etc/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$(brew --prefix vulkan-loader)/lib" >> $GITHUB_ENV
      - run: rustup update stable && rustup default stable
      - name: Run CI tests (Linux OpenGL via Xvfb)
        if: startsWith(matrix.runs-on, 'ubuntu') && matrix.backend == 'opengl'
        run: xvfb-run -a --server-args="-screen 0 1280x1024x24" just ci-test ${{ matrix.backend }}
      - name: Run CI tests
        if: ${{ !(startsWith(matrix.runs-on, 'ubuntu') && matrix.backend == 'opengl') }}
        run: just ci-test ${{ matrix.backend }}

  test-msrv:
    name: Test MSRV ${{ matrix.runs-on }} - ${{ matrix.backend }} - Precompiled ${{ matrix.precompiled }}
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86
          - runs-on: ubuntu-latest
            backend: vulkan
            precompiled: 0
            amalgam: 0
          - runs-on: ubuntu-latest
            backend: opengl
            precompiled: 0
            amalgam: 0
          # Linux ARM
          - runs-on: ubuntu-24.04-arm
            backend: opengl
            precompiled: 0
            amalgam: 0
          # macOS ARM
          - runs-on: macos-latest
            backend: metal
            precompiled: 0
            amalgam: 0
          - runs-on: macos-latest
            backend: vulkan
            precompiled: 0
            amalgam: 0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
        with: { tool: 'just' }
      - run: echo "MLN_PRECOMPILE=${{ matrix.precompiled }}" >> $GITHUB_ENV
      - run: echo "MLN_CORE_LIBRARY_USE_AMALGAM=${{ matrix.amalgam }}" >> $GITHUB_ENV
      - run: just env-info install-dependencies '${{ matrix.backend }}'
      - if: startsWith(matrix.runs-on, 'macos') && matrix.backend == 'vulkan'
        run: |
          echo "VK_ICD_FILENAMES=$(brew --prefix molten-vk)/etc/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$(brew --prefix vulkan-loader)/lib" >> $GITHUB_ENV
      - name: Read MSRV
        id: msrv
        run: echo "value=$(just get-msrv)" >> $GITHUB_OUTPUT
      - name: Install MSRV Rust ${{ steps.msrv.outputs.value }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.msrv.outputs.value }}
      - name: Run CI tests (MSRV, Linux OpenGL via Xvfb)
        if: startsWith(matrix.runs-on, 'ubuntu') && matrix.backend == 'opengl'
        run: xvfb-run -a --server-args="-screen 0 1280x1024x24" just ci_mode=0 ci-test-msrv ${{ matrix.backend }}  # Ignore warnings in MSRV
      - name: Run CI tests (MSRV)
        if: ${{ !(startsWith(matrix.runs-on, 'ubuntu') && matrix.backend == 'opengl') }}
        run: just ci_mode=0 ci-test-msrv ${{ matrix.backend }}  # Ignore warnings in MSRV

  # This final step is needed to mark the whole workflow as successful
  # Don't change its name - it is used by the merge protection rules
  ci-passed:
    needs: [ lint, test, test-msrv ]
    if: always()
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Result of the needed steps
        run: echo "${{ toJSON(needs) }}"
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

  # Release unpublished packages or create a PR with changes
  release-plz:
    needs: [ ci-passed ]
    if: |
      always()
      && needs.ci-passed.result == 'success'
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository_owner == 'mapvina'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    env:
      MLN_PRECOMPILE: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io if crate's version is newer
        uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db # v0.5.129
        id: release
        with: { command: release }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.release.outputs.releases_created == 'false' }}
        name: If version is the same, create a PR proposing new version and changelog for the next release
        uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db # v0.5.129
        with: { command: release-pr }
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
